on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v3

      - name: Install SFML
        run: sudo apt install libsfml-dev

      - name: Install Codecov
        run: sudo pip install codecov

      - name: Download magic_enum
        run: |
          cd ..
          git clone https://github.com/Neargye/magic_enum
          cd -

      - name: Install magic_enum
        run: |
          cd ../magic_enum
          cmake .
          make
          cd -

      - name: qmake
        run: qmake "DEFINES+=LOGIC_ONLY" game.pro

      - name: make
        run: make debug

      - name: run
        run: ./conquer_chess --test

      - name: Measure codecov 1
        run: ./scripts/get_code_cov.sh

      - name: Measure codecov 2
        run: codecov

      - name: Measure codecov 3
        run: bash <(curl -s https://codecov.io/bash)

      - name: clean for release build
        run: make clean

      - name: qmake
        run: qmake game.pro

      - name: make
        run: make release --silent

